/**
 * OWNERSHIP: Bersama (konfigurasi bersama)
 * Katalog produk + harga dasar (basePrice) per produk. basePrice di sini jadi
 * masukan buildPriceQuote di lib/server/pricing.ts. Lihat ARCHITECTURE.md.
 */
export interface Product {
  id: string
  category: 'tshirts' | 'jackets' | 'polo' | 'sport'
  name: string
  description: string
  shortDescription?: string
  colors: number
  sizes: string
  material: string
  badge?: 'Populer' | 'Best Seller' | 'Turun Harga'
  thumbnailImage?: string
  image?: string
  basePrice?: number
}

export const productsByCategory: Record<string, Product[]> = {
  tshirts: [
    {
      id: '1',
      category: 'tshirts',
      name: 'Premium Cotton T-Shirt',
      description: 'Kaos katun premium berkualitas tinggi',
      shortDescription: 'Kaos katun premium',
      colors: 8,
      sizes: 'S-5XL',
      material: '100% Cotton, 200 GSM',
      badge: 'Populer',
      basePrice: 85000,
      image: '/tshirts model/Premium Cotton T-Shirt.png',
    },
    {
      id: '2',
      category: 'tshirts',
      name: 'Basic White T-Shirt',
      description: 'Kaos polos putih standart',
      shortDescription: 'Kaos polos putih',
      colors: 5,
      sizes: 'S-4XL',
      material: '100% Cotton, 160 GSM',
      badge: 'Best Seller',
      basePrice: 65000,
      image: '/tshirts model/Basic White T-Shirt.png',
    },
    {
      id: '3',
      category: 'tshirts',
      name: 'Vintage Blend T-Shirt',
      description: 'Kaos dengan tekstur vintage',
      shortDescription: 'Kaos vintage blend',
      colors: 6,
      sizes: 'S-3XL',
      material: 'Cotton Blend, 180 GSM',
      basePrice: 75000,
      image: '/tshirts model/Vintage Blend T-Shirt.png',
    },
    {
      id: '4',
      category: 'tshirts',
      name: 'Performance T-Shirt',
      description: 'Kaos teknologi anti keringat',
      shortDescription: 'Kaos performance',
      colors: 4,
      sizes: 'XS-2XL',
      material: 'Polyester, 150 GSM',
      badge: 'Turun Harga',
      basePrice: 72000,
      image: '/tshirts model/Performance T-Shirt.png',
    },
    {
      id: '5',
      category: 'tshirts',
      name: 'Oversized T-Shirt',
      description: 'Kaos model besar relaksed fit',
      shortDescription: 'Kaos oversized',
      colors: 7,
      sizes: 'S-5XL',
      material: '100% Cotton, 220 GSM',
      basePrice: 82000,
      image: '/tshirts model/Oversized T-Shirt.png',
    },
    {
      id: '6',
      category: 'tshirts',
      name: 'Fitted T-Shirt',
      description: 'Kaos model ketat premium',
      shortDescription: 'Kaos fitted',
      colors: 6,
      sizes: 'XS-2XL',
      material: '100% Cotton, 180 GSM',
      basePrice: 78000,
      image: '/tshirts model/Fitted T-Shirt.png',
    },
    {
      id: '7',
      category: 'tshirts',
      name: 'Sports T-Shirt',
      description: 'Kaos untuk kegiatan olahraga',
      shortDescription: 'Kaos olahraga',
      colors: 5,
      sizes: 'S-4XL',
      material: 'Dry-fit Polyester, 140 GSM',
      badge: 'Populer',
      basePrice: 95000,
      image: '/tshirts model/Sports T-Shirt.png',
    },
    {
      id: '8',
      category: 'tshirts',
      name: 'Luxury Cotton T-Shirt',
      description: 'Kaos kotton mewah premium',
      shortDescription: 'Kaos luxury cotton',
      colors: 8,
      sizes: 'S-3XL',
      material: 'Premium Cotton, 240 GSM',
      basePrice: 120000,
      image: '/tshirts model/Luxury Cotton T-Shirt.png',
    },
  ],
  jackets: [
    {
      id: 'j1',
      category: 'jackets',
      name: 'Fleece Hoodie',
      description: 'Hoodie fleece hangat dan nyaman',
      shortDescription: 'Hoodie fleece',
      colors: 6,
      sizes: 'S-3XL',
      material: 'Fleece Blend, 280 GSM',
      badge: 'Populer',
      basePrice: 180000,
    },
    {
      id: 'j2',
      category: 'jackets',
      name: 'Bomber Jacket',
      description: 'Jaket bomber modern trendi',
      shortDescription: 'Jaket bomber',
      colors: 4,
      sizes: 'S-2XL',
      material: 'Polyester, 200 GSM',
      basePrice: 195000,
    },
    {
      id: 'j3',
      category: 'jackets',
      name: 'Windbreaker Jacket',
      description: 'Jaket tahan angin waterproof',
      shortDescription: 'Jaket windbreaker',
      colors: 5,
      sizes: 'S-3XL',
      material: 'Nylon, 150 GSM',
      basePrice: 165000,
    },
    {
      id: 'j4',
      category: 'jackets',
      name: 'Denim Jacket',
      description: 'Jaket denim klasik timeless',
      shortDescription: 'Jaket denim',
      colors: 3,
      sizes: 'S-2XL',
      material: 'Denim 100% Cotton, 320 GSM',
      basePrice: 215000,
    },
    {
      id: 'j5',
      category: 'jackets',
      name: 'Zip Hoodie',
      description: 'Hoodie dengan resleting depan',
      shortDescription: 'Hoodie dengan zip',
      colors: 7,
      sizes: 'S-3XL',
      material: 'Cotton Blend, 250 GSM',
      badge: 'Best Seller',
      basePrice: 185000,
    },
    {
      id: 'j6',
      category: 'jackets',
      name: 'Puffer Jacket',
      description: 'Jaket tebal hangat musim dingin',
      shortDescription: 'Jaket puffer',
      colors: 5,
      sizes: 'S-2XL',
      material: 'Polyester, 350 GSM',
      basePrice: 275000,
    },
  ],
  polo: [
    {
      id: 'p1',
      category: 'polo',
      name: 'Classic Polo Shirt',
      description: 'Polo shirt klasik elegant',
      shortDescription: 'Polo classic',
      colors: 8,
      sizes: 'S-3XL',
      material: '100% Cotton Pique, 200 GSM',
      badge: 'Populer',
      basePrice: 95000,
    },
    {
      id: 'p2',
      category: 'polo',
      name: 'Performance Polo',
      description: 'Polo shirt berteknologi moisture wicking',
      shortDescription: 'Polo performance',
      colors: 6,
      sizes: 'S-2XL',
      material: 'Polyester Blend, 160 GSM',
      badge: 'Best Seller',
      basePrice: 105000,
    },
    {
      id: 'p3',
      category: 'polo',
      name: 'Long Sleeve Polo',
      description: 'Polo dengan lengan panjang',
      shortDescription: 'Polo lengan panjang',
      colors: 5,
      sizes: 'S-3XL',
      material: '100% Cotton Pique, 220 GSM',
      basePrice: 115000,
    },
    {
      id: 'p4',
      category: 'polo',
      name: 'Slim Fit Polo',
      description: 'Polo dengan potongan slim fit',
      shortDescription: 'Polo slim fit',
      colors: 7,
      sizes: 'XS-2XL',
      material: '100% Cotton, 180 GSM',
      badge: 'Turun Harga',
      basePrice: 88000,
    },
    {
      id: 'p5',
      category: 'polo',
      name: 'Oversized Polo',
      description: 'Polo dengan model oversized trendy',
      shortDescription: 'Polo oversized',
      colors: 6,
      sizes: 'S-3XL',
      material: 'Cotton Blend, 200 GSM',
      basePrice: 98000,
    },
    {
      id: 'p6',
      category: 'polo',
      name: 'Golf Polo Shirt',
      description: 'Polo shirt khusus untuk olahraga golf',
      shortDescription: 'Polo golf',
      colors: 4,
      sizes: 'S-2XL',
      material: 'Dry-fit Polyester, 140 GSM',
      basePrice: 135000,
    },
  ],
  sport: [
    {
      id: 's1',
      category: 'sport',
      name: 'Running T-Shirt',
      description: 'Kaos lari berteknologi anti keringat',
      shortDescription: 'Kaos lari',
      colors: 5,
      sizes: 'S-2XL',
      material: 'Dry-fit Polyester, 130 GSM',
      badge: 'Populer',
      basePrice: 110000,
    },
    {
      id: 's2',
      category: 'sport',
      name: 'Basketball Jersey',
      description: 'Jersey basket premium dengan mesh',
      shortDescription: 'Jersey basket',
      colors: 6,
      sizes: 'S-3XL',
      material: 'Mesh Polyester, 120 GSM',
      basePrice: 125000,
    },
    {
      id: 's3',
      category: 'sport',
      name: 'Training Shorts',
      description: 'Celana training nyaman breathable',
      shortDescription: 'Celana training',
      colors: 4,
      sizes: 'S-2XL',
      material: 'Polyester Blend, 140 GSM',
      basePrice: 85000,
    },
    {
      id: 's4',
      category: 'sport',
      name: 'Gym Tank Top',
      description: 'Tank top untuk gym dan fitness',
      shortDescription: 'Tank top gym',
      colors: 5,
      sizes: 'XS-2XL',
      material: 'Dry-fit Polyester, 110 GSM',
      basePrice: 95000,
    },
    {
      id: 's5',
      category: 'sport',
      name: 'Soccer Jersey',
      description: 'Jersey sepak bola dengan logo custom',
      shortDescription: 'Jersey sepak bola',
      colors: 7,
      sizes: 'S-3XL',
      material: 'Mesh Polyester, 130 GSM',
      badge: 'Best Seller',
      basePrice: 145000,
    },
    {
      id: 's6',
      category: 'sport',
      name: 'Cycling Jersey',
      description: 'Jersey sepeda dengan design aerodynamic',
      shortDescription: 'Jersey sepeda',
      colors: 6,
      sizes: 'S-2XL',
      material: 'Polyester Technical, 150 GSM',
      basePrice: 155000,
    },
  ],
}

export function getProductById(productId: string, category: string): Product | undefined {
  const products = productsByCategory[category]
  return products?.find(p => p.id === productId)
}

export function getAllProductsFlat(): Product[] {
  return Object.values(productsByCategory).flat()
}
