/**
 * lib/config/templates.ts
 * 
 * Starter template presets for the canvas editor.
 * Each template is a serialized canvas state (same format as serializeUserObjects)
 * that can be loaded directly via util.enlivenObjects.
 * 
 * All templates are hardcoded for zero network dependency (offline-first).
 */

export interface CanvasTemplate {
  id: string
  name: string
  description: string
  zone: string // which zone this template is designed for
  objects: object[] // Fabric.js serialized objects (USER_PROPERTIES format)
}

export const STARTER_TEMPLATES: CanvasTemplate[] = [
  {
    id: 'tpl-text-center',
    name: 'Teks Tengah',
    description: 'Teks besar di tengah area cetak depan',
    zone: 'front',
    objects: [
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 290,
        width: 160,
        fill: '#000000',
        text: 'NAMA BRAND',
        fontSize: 32,
        fontWeight: 'bold',
        fontFamily: 'Oswald',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-text-center-1',
        name: 'NAMA BRAND',
        view: 'front',
      },
    ],
  },
  {
    id: 'tpl-left-chest',
    name: 'Logo Kiri Dada',
    description: 'Posisi logo standar sablon kiri dada',
    zone: 'front',
    objects: [
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'left',
        originY: 'top',
        left: 148,
        top: 160,
        width: 90,
        fill: '#000000',
        text: 'LOGO',
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Montserrat',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-left-chest-1',
        name: 'LOGO',
        view: 'front',
      },
    ],
  },
  {
    id: 'tpl-two-line',
    name: 'Dua Baris Teks',
    description: 'Nama brand + tagline dua baris',
    zone: 'front',
    objects: [
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 270,
        width: 180,
        fill: '#000000',
        text: 'NAMA BRAND',
        fontSize: 36,
        fontWeight: 'bold',
        fontFamily: 'Oswald',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-two-line-1',
        name: 'Brand Name',
        view: 'front',
      },
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 315,
        width: 160,
        fill: '#666666',
        text: 'Est. 2024',
        fontSize: 16,
        fontWeight: 'normal',
        fontFamily: 'Inter',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-two-line-2',
        name: 'Tagline',
        view: 'front',
      },
    ],
  },
  {
    id: 'tpl-back-full',
    name: 'Teks Punggung Penuh',
    description: 'Teks besar di punggung (back zone)',
    zone: 'back',
    objects: [
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 295,
        width: 170,
        fill: '#000000',
        text: 'COMMUNITY',
        fontSize: 38,
        fontWeight: 'bold',
        fontFamily: 'Montserrat',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-back-full-1',
        name: 'COMMUNITY',
        view: 'back',
      },
    ],
  },
  {
    id: 'tpl-box-text',
    name: 'Kotak + Teks',
    description: 'Shape kotak dengan teks di tengah',
    zone: 'front',
    objects: [
      {
        type: 'rect',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 290,
        width: 160,
        height: 70,
        fill: '#000000',
        rx: 4,
        ry: 4,
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-box-text-rect',
        name: 'Box',
        view: 'front',
      },
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 290,
        width: 140,
        fill: '#FFFFFF',
        text: 'BRAND',
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: 'Oswald',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-box-text-label',
        name: 'BRAND',
        view: 'front',
      },
    ],
  },
  {
    id: 'tpl-number-jersey',
    name: 'Nomor Jersey',
    description: 'Nomor besar gaya jersey olahraga',
    zone: 'front',
    objects: [
      {
        type: 'textbox',
        version: '6.0.0',
        originX: 'center',
        originY: 'center',
        left: 250,
        top: 290,
        width: 180,
        fill: '#000000',
        text: '10',
        fontSize: 80,
        fontWeight: 'bold',
        fontFamily: 'Montserrat',
        textAlign: 'center',
        selectable: true,
        hasControls: true,
        hasBorders: true,
        lockRotation: true,
        id: 'tpl-jersey-number',
        name: 'Nomor Jersey',
        view: 'front',
      },
    ],
  },
]
